
package mockPackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService1", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService1 {


    /**
     * 
     * @param value
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetData", action = "http://tempuri.org/IService1/GetData")
    @WebResult(name = "GetDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetData", targetNamespace = "http://tempuri.org/", className = "mockPackage.GetData")
    @ResponseWrapper(localName = "GetDataResponse", targetNamespace = "http://tempuri.org/", className = "mockPackage.GetDataResponse")
    public String getData(
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/")
        Integer value);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IService1/commitOrder")
    @WebResult(name = "commitOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "commitOrder", targetNamespace = "http://tempuri.org/", className = "mockPackage.CommitOrder")
    @ResponseWrapper(localName = "commitOrderResponse", targetNamespace = "http://tempuri.org/", className = "mockPackage.CommitOrderResponse")
    public String commitOrder();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IService1/getTransferOption")
    @WebResult(name = "getTransferOptionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getTransferOption", targetNamespace = "http://tempuri.org/", className = "mockPackage.GetTransferOption")
    @ResponseWrapper(localName = "getTransferOptionResponse", targetNamespace = "http://tempuri.org/", className = "mockPackage.GetTransferOptionResponse")
    public String getTransferOption();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IService1/setTransferOption")
    @WebResult(name = "setTransferOptionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "setTransferOption", targetNamespace = "http://tempuri.org/", className = "mockPackage.SetTransferOption")
    @ResponseWrapper(localName = "setTransferOptionResponse", targetNamespace = "http://tempuri.org/", className = "mockPackage.SetTransferOptionResponse")
    public String setTransferOption();

    /**
     * 
     * @param composite
     * @return
     *     returns mockPackage.CompositeType
     */
    @WebMethod(operationName = "GetDataUsingDataContract", action = "http://tempuri.org/IService1/GetDataUsingDataContract")
    @WebResult(name = "GetDataUsingDataContractResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDataUsingDataContract", targetNamespace = "http://tempuri.org/", className = "mockPackage.GetDataUsingDataContract")
    @ResponseWrapper(localName = "GetDataUsingDataContractResponse", targetNamespace = "http://tempuri.org/", className = "mockPackage.GetDataUsingDataContractResponse")
    public CompositeType getDataUsingDataContract(
        @WebParam(name = "composite", targetNamespace = "http://tempuri.org/")
        CompositeType composite);

}
